# Generated by Django 3.2.12 on 2024-03-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFTransmitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtable',
            name='Created0n',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Created0n',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
