# Generated by Django 3.2.12 on 2024-03-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFTransmitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=20)),
                ('pwr', models.CharField(max_length=100)),
                ('pw_usec', models.IntegerField()),
                ('action', models.CharField(max_length=30)),
                ('time_stamp', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
