# Generated by Django 3.2.12 on 2024-03-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFTransmitter', '0003_alter_logtable_created0n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtable',
            name='Created0n',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
