# Generated by Django 3.2.12 on 2024-03-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFTransmitter', '0004_alter_logtable_created0n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logtable',
            name='Created0n',
            field=models.DateTimeField(),
        ),
    ]
