# Generated by Django 3.2.12 on 2024-03-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFTransmitter', '0007_auto_20240312_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pw_usec',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
