# Generated by Django 3.2.12 on 2024-03-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFTransmitter', '0009_auto_20240313_1042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logtable',
            old_name='timestamp',
            new_name='timestampn',
        ),
        migrations.AlterField(
            model_name='logtable',
            name='pwr',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pw_usec',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pwr',
            field=models.IntegerField(null=True),
        ),
    ]
