# Generated by Django 3.2.12 on 2024-03-13 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RFTransmitter', '0010_auto_20240313_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logtable',
            old_name='timestampn',
            new_name='timestamp',
        ),
    ]
